spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/fungimapper
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    testOnBorrow: true
    hikari:
      idle-timeout: 10000
      minimumIdle: 2
      maximum-pool-size: 20
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
  liquibase:
    change-log: classpath:changelog.xml
  jpa:
    hibernate:
      jdbc:
        batch_size: 100
    open-in-view: true
  log4j.logger.httpclient.wire: DEBUG
